<?php
 /**
 * Cache 
 * name: Cc\Mvc\SelectorControllers
 * Expire: 2019-02-25 17:51:51
*/
return array (
  0 => 
  array (
    'Cc\\Mvc\\Cuser' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Cuser.php',
    'Cc\\Mvc\\Csettings' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Csettings.php',
    'Cc\\Mvc\\Cnotificaciones' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Cnotificaciones.php',
    'Cc\\Mvc\\Calimentos' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Calimentos.php',
    'Cc\\Mvc\\Cgalpones' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Cgalpones.php',
    'Cc\\Mvc\\Caves' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Caves.php',
    'Cc\\Mvc\\Chuevos' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Chuevos.php',
    'Cc\\Mvc\\CAves' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\CAves.php',
    'Cc\\Mvc\\Cindex' => 'D:\\Programacion\\php\\polleras\\protected\\controllers\\Cindex.php',
  ),
  1 => 1551113511,
);?>