<?php
 /**
 * Cache 
 * name: AutoloadCore
 * Expire: 2018-12-03 22:10:59
*/
return array (
  0 => 
  array (
    'Cc\\Mvc\\Caves' => 'F:\\Programacion\\php\\polleras\\protected\\controllers\\CAves.php',
    'Cc\\Mvc\\CostumController' => 'F:\\Programacion\\php\\polleras\\protected\\model\\CostumController.php',
    'Cc\\Mvc\\Auth' => 'F:\\Programacion\\php\\polleras\\protected\\model\\Auth.php',
    'Cc\\Mvc\\TablaModel\\usuarios' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\usuarios.php',
    'Cc\\Mvc\\TablaModel\\galpones' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\galpones.php',
    'Cc\\Mvc\\TablaModel\\produccion_huevos' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\produccion_huevos.php',
    'Cc\\Mvc\\TablaModel\\venta_huevos' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_huevos.php',
    'Cc\\Mvc\\TablaModel\\mortalidad' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\mortalidad.php',
    'Cc\\Mvc\\TablaModel\\venta_aves' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_aves.php',
    'Cc\\Mvc\\TablaModel\\compra_aves' => 'F:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\compra_aves.php',
  ),
  1 => 1543891259,
);?>