<?php
 /**
 * Cache 
 * name: AutoloadCore
 * Expire: 2018-12-14 06:35:20
*/
return array (
  0 => 
  array (
    'Cc\\Mvc\\Auth' => 'I:\\Programacion\\php\\polleras\\protected\\model\\Auth.php',
    'Cc\\Mvc\\CostumController' => 'I:\\Programacion\\php\\polleras\\protected\\model\\CostumController.php',
    'Cc\\Mvc\\ReporteFPDF' => 'I:\\Programacion\\php\\polleras\\protected\\model\\ReporteFPDF.php',
    'Cc\\Mvc\\TablaModel\\asistencia' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\asistencia.php',
    'Cc\\Mvc\\TablaModel\\compra_alimentos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\compra_alimentos.php',
    'Cc\\Mvc\\TablaModel\\compra_aves' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\compra_aves.php',
    'Cc\\Mvc\\TablaModel\\compra_medicinas' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\compra_medicinas.php',
    'Cc\\Mvc\\TablaModel\\consumo_alimentos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\consumo_alimentos.php',
    'Cc\\Mvc\\TablaModel\\consumo_medicinas' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\consumo_medicinas.php',
    'Cc\\Mvc\\TablaModel\\empleados' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\empleados.php',
    'Cc\\Mvc\\TablaModel\\galpones' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\galpones.php',
    'Cc\\Mvc\\TablaModel\\medicinas' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\medicinas.php',
    'Cc\\Mvc\\TablaModel\\mortalidad' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\mortalidad.php',
    'Cc\\Mvc\\TablaModel\\notificaciones' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\notificaciones.php',
    'Cc\\Mvc\\TablaModel\\pago_nomina' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\pago_nomina.php',
    'Cc\\Mvc\\TablaModel\\produccion_huevos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\produccion_huevos.php',
    'Cc\\Mvc\\TablaModel\\sessiones' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\sessiones.php',
    'Cc\\Mvc\\TablaModel\\usuarios' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\usuarios.php',
    'Cc\\Mvc\\TablaModel\\venta_aves' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_aves.php',
    'Cc\\Mvc\\TablaModel\\venta_huevos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_huevos.php',
    'Cc\\Mvc\\CompraAlimentosForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Alimentos.php',
    'Cc\\Mvc\\ConsumoAlimentosForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Alimentos.php',
    'Cc\\Mvc\\CompraAvesForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Aves.php',
    'Cc\\Mvc\\MortalidadAvesForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Aves.php',
    'Cc\\Mvc\\EmpleadosForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Empleados.php',
    'Cc\\Mvc\\PagoNominaForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Empleados.php',
    'Cc\\Mvc\\Form' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Form.php',
    'Cc\\Mvc\\GalponesForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Galpones.php',
    'Cc\\Mvc\\ProduccionHuevosForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Huevos.php',
    'Cc\\Mvc\\VentaHuevosForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Huevos.php',
    'Cc\\Mvc\\LoginUserForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\LoginUserForm.php',
    'Cc\\Mvc\\MedicinasForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Medicinas.php',
    'Cc\\Mvc\\CompraMedicinasForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Medicinas.php',
    'Cc\\Mvc\\ConsumoMedicinasForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Medicinas.php',
    'Cc\\Mvc\\SettingsForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\Settings.php',
    'Cc\\Mvc\\UserForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\UserForm.php',
    'Cc\\Mvc\\EditarUserForm' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\UserForm.php',
    'Cc\\Mvc\\FormEditarContrasena' => 'I:\\Programacion\\php\\polleras\\protected\\model\\FormModel\\UserForm.php',
    'Cc\\Mvc\\Caves' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\CAves.php',
  ),
  1 => 1544785520,
);?>