<?php
 /**
 * Cache 
 * name: AutoloadCore
 * Expire: 2018-12-11 17:52:00
*/
return array (
  0 => 
  array (
    'Cc\\Mvc\\Caves' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\CAves.php',
    'Cc\\Mvc\\CostumController' => 'I:\\Programacion\\php\\polleras\\protected\\model\\CostumController.php',
    'Cc\\Mvc\\Auth' => 'I:\\Programacion\\php\\polleras\\protected\\model\\Auth.php',
    'Cc\\Mvc\\TablaModel\\usuarios' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\usuarios.php',
    'Cc\\Mvc\\TablaModel\\galpones' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\galpones.php',
    'Cc\\Mvc\\TablaModel\\consumo_alimentos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\consumo_alimentos.php',
    'Cc\\Mvc\\TablaModel\\compra_aves' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\compra_aves.php',
    'Cc\\Mvc\\TablaModel\\venta_aves' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_aves.php',
    'Cc\\Mvc\\TablaModel\\mortalidad' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\mortalidad.php',
    'Cc\\Mvc\\TablaModel\\produccion_huevos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\produccion_huevos.php',
    'Cc\\Mvc\\TablaModel\\venta_huevos' => 'I:\\Programacion\\php\\polleras\\protected\\model\\DBtablaModel\\venta_huevos.php',
  ),
  1 => 1544547120,
);?>