<?php
 /**
 * Cache 
 * name: Cc\Mvc\SelectorControllers
 * Expire: 2018-12-11 18:59:28
*/
return array (
  0 => 
  array (
    'Cc\\Mvc\\Cnotificaciones' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cnotificaciones.php',
    'Cc\\Mvc\\Calimentos' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Calimentos.php',
    'Cc\\Mvc\\Cgalpones' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cgalpones.php',
    'Cc\\Mvc\\Caves' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Caves.php',
    'Cc\\Mvc\\Cuser' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cuser.php',
    'Cc\\Mvc\\Csettings' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Csettings.php',
    'Cc\\Mvc\\Cindex' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cindex.php',
    'Cc\\Mvc\\Chuevos' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Chuevos.php',
    'Cc\\Mvc\\CAves' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\CAves.php',
    'Cc\\Mvc\\Cempleados' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cempleados.php',
    'Cc\\Mvc\\Cmedicinas' => 'I:\\Programacion\\php\\polleras\\protected\\controllers\\Cmedicinas.php',
  ),
  1 => 1544551168,
);?>